[package]
name = "optom"
version = "0.1.0"
authors = ["Peter Sutcliffe <sutcliffe_peter@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.15.0"
strum_macros = "0.15.0"